language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"
script: "lektor build"
deploy:
  fqdn: 'https://jeff-tian.github.io'
  provider: script
  script: "lektor deploy ghpages"
  on:
    branch: src
